### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by shiyongde** [openai/gradient-checkpointing#12]
I update tensorflow to 1.5 ,and with cuda 9 cudnn 7 
after install tf-nightly-gpu  , I got core dumped

$python -c 'import tensorflow '
Segmentation fault (core dumped)

Program terminated with signal 11, Segmentation fault.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `python -c import tensorflow '.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fa181219976 in _dl_relocate_object () from /lib64/ld-linux-x86-64.so.2
Missing separate debuginfos, use: debuginfo-install python-2.7.5-58.el7.x86_64
(gdb) bt
#0  0x00007fa181219976 in _dl_relocate_object () from /lib64/ld-linux-x86-64.so.2
#1  0x00007fa181221b3c in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#2  0x00007fa18121d1b4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#3  0x00007fa1812211ab in _dl_open () from /lib64/ld-linux-x86-64.so.2
#4  0x00007fa180a2302b in dlopen_doit () from /lib64/libdl.so.2
#5  0x00007fa18121d1b4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#6  0x00007fa180a2362d in _dlerror_run () from /lib64/libdl.so.2
#7  0x00007fa180a230c1 in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
#8  0x00007fa179a261f1 in py_dl_open () from /usr/lib64/python2.7/lib-dynload/_ctypes.so
#9  0x00007fa180f26bb0 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#10 0x00007fa180f28efd in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#11 0x00007fa180eb2858 in function_call () from /lib64/libpython2.7.so.1.0
#12 0x00007fa180e8d9a3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#13 0x00007fa180e9c995 in instancemethod_call () from /lib64/libpython2.7.so.1.0
#14 0x00007fa180e8d9a3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#15 0x00007fa180ee4947 in slot_tp_init () from /lib64/libpython2.7.so.1.0
#16 0x00007fa180ee365f in type_call () from /lib64/libpython2.7.so.1.0
#17 0x00007fa180e8d9a3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#18 0x00007fa180f220f6 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#19 0x00007fa180f28efd in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#20 0x00007fa180f29002 in PyEval_EvalCode () from /lib64/libpython2.7.so.1.0
#21 0x00007fa180f38dec in PyImport_ExecCodeModuleEx () from /lib64/libpython2.7.so.1.0
#22 0x00007fa180f39068 in load_source_module () from /lib64/libpython2.7.so.1.0
#23 0x00007fa180f39d01 in import_submodule () from /lib64/libpython2.7.so.1.0
#24 0x00007fa180f39fe6 in load_next () from /lib64/libpython2.7.so.1.0
#25 0x00007fa180f3a92e in PyImport_ImportModuleLevel () from /lib64/libpython2.7.so.1.0
#26 0x00007fa180f1dbdf in builtin___import__ () from /lib64/libpython2.7.so.1.0
#27 0x00007fa180e8d9a3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#28 0x00007fa180f1f7b7 in PyEval_CallObjectWithKeywords () from /lib64/libpython2.7.so.1.0
#29 0x00007fa180f24475 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#30 0x00007fa180f28efd in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#31 0x00007fa180f29002 in PyEval_EvalCode () from /lib64/libpython2.7.so.1.0
#32 0x00007fa180f38dec in PyImport_ExecCodeModuleEx () from /lib64/libpython2.7.so.1.0
#33 0x00007fa180f39068 in load_source_module () from /lib64/libpython2.7.so.1.0
#34 0x00007fa180f39d01 in import_submodule () from /lib64/libpython2.7.so.1.0
#35 0x00007fa180f3a1ff in ensure_fromlist () from /lib64/libpython2.7.so.1.0
#36 0x00007fa180f3aa3a in PyImport_ImportModuleLevel () from /lib64/libpython2.7.so.1.0
#37 0x00007fa180f1dbdf in builtin___import__ () from /lib64/libpython2.7.so.1.0
#38 0x00007fa180e8d9a3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#39 0x00007fa180f1f7b7 in PyEval_CallObjectWithKeywords () from /lib64/libpython2.7.so.1.0
#40 0x00007fa180f24475 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#41 0x00007fa180f2657d in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#42 0x00007fa180f2657d in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#43 0x00007fa180f28efd in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#44 0x00007fa180eb2858 in function_call () from /lib64/libpython2.7.so.1.0
#45 0x00007fa180e8d9a3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#46 0x00007fa180f1f7b7 in PyEval_CallObjectWithKeywords () from /lib64/libpython2.7.so.1.0
#47 0x00007fa180f43c9c in PyErr_PrintEx () from /lib64/libpython2.7.so.1.0
#48 0x00007fa180f44c9c in PyRun_SimpleStringFlags () from /lib64/libpython2.7.so.1.0
#49 0x00007fa180f55520 in Py_Main () from /lib64/libpython2.7.so.1.0
#50 0x00007fa18017cb15 in __libc_start_main () from /lib64/libc.so.6
#51 0x000000000040071e in _start ()

**Comment by yaroslavvb** [comment]
Our tool is Python-only so any segfault must be due to underlying libraries. If you can reproduce this with small example, it may make sense to file it on TensorFlow git repo
