### ISSUE TITLE
RNN while loop context error

### ISSUE THREAD

**Issue by MaxOSmith** [openai/gradient-checkpointing#7]
## Problem Description
When stopping the gradient on a node in a while loop a value error is thrown. Stack trace:
```
2018-01-18 16:56:14.252388: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing Curl library
Traceback (most recent call last):
  File "test.py", line 256, in <module>
    data, data_lengths, target, target_lengths, training, hparams)
  File "test.py", line 52, in __init__
    self.optimize
  File "test.py", line 21, in decorator
    setattr(self, attribute, function(self))
  File "test.py", line 189, in optimize
    self.loss, params, checkpoints="speed")
  File "/u/smithmax/Projects/_/memory_saving_gradients.py", line 197, in gradients
    grad_node = tf.stop_gradient(x, name=x.op.name+"_sg")
  File "/u/smithmax/.conda/envs/tf_nightly3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5220, in stop_gradient
    "StopGradient", input=input, name=name)
  File "/u/smithmax/.conda/envs/tf_nightly3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/u/smithmax/.conda/envs/tf_nightly3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3172, in create_op
    op_def=op_def)
  File "/u/smithmax/.conda/envs/tf_nightly3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1659, in __init__
    self._control_flow_post_processing()
  File "/u/smithmax/.conda/envs/tf_nightly3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1668, in _control_flow_post_processing
    control_flow_util.CheckInputFromValidContext(self, input_tensor.op)
  File "/u/smithmax/.conda/envs/tf_nightly3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_util.py", line 260, in CheckInputFromValidContext
    raise ValueError(error_msg + " See info log for more details.")
ValueError: Cannot use 'decoder/while/BasicDecoderStep/gru_cell/MatMul/Enter' as input to 'decoder/while/BasicDecoderStep/gru_cell/MatMul/Enter_sg' because 'decoder/while/BasicDecoderStep/gru_cell/MatMul/Enter' is in a while loop. See info log for more details.
```
I'm not familiar with graph editing, so I don't have an idea of a direction on where to start. :(

## System Information
- **Python version:** 3.6.0 (64-bit)
- **OS Platform**: Debian 4.9.65 x86_x64 
- **TF version:** `tf-nightly-gpu==1.6.0.dev20180117`

## Code to Reproduce
This is just a seq2seq graph class, sorry that it's a little messy.

There's various lines for different potential checkpoints commented out, and only one is currently uncommented. It doesn't appear to work for any of the checkpoint candidates.

```
import functools
import tensorflow as tf

import memory_saving_gradients as memory_saving_gradients


_CHECK = "checkpoints"


def lazy_loading_property(function):
    """ Lazy loading decorator.

    Source: https://danijar.com/structuring-your-tensorflow-models/
    """
    attribute = "_cache_" + function.__name__

    @property
    @functools.wraps(function)
    def decorator(self):
        if not hasattr(self, attribute):
            setattr(self, attribute, function(self))
        return getattr(self, attribute)

    return decorator


class RNNGraph:

    def __init__(
            self, data, data_lengths, target, target_lengths,
            training, hyperparams):
        self.data = data
        self.data_lengths = data_lengths
        self.target = target
        self.target_lengths = target_lengths
        self.training = training
        self._hyperparams = hyperparams

        # defined in time for `tf.initialize_variables()`.
        self.inference
        self.optimize
        self.loss

    @lazy_loading_property
    def encoder_cells(self):
        """ Encoding cells.

        :return: `RNNCell` object.
        """
        encoder_cells = tf.nn.rnn_cell.GRUCell(
            self._hyperparams["num_units"],
            kernel_initializer=self._hyperparams["initializer"],
            bias_initializer=self._hyperparams["initializer"])
        return encoder_cells

    @lazy_loading_property
    def decoder_cells(self):
        """ Decoding cells.

        :return: `RNNCell` object.
        """
        decoder_cells = tf.nn.rnn_cell.GRUCell(
            self._hyperparams["num_units"],
            kernel_initializer=self._hyperparams["initializer"],
            bias_initializer=self._hyperparams["initializer"])
        return decoder_cells

    @lazy_loading_property
    def inference(self, open_loop=False):
        """ Perform inference on the graph.

        :param open_loop:
        :return:
        """
        # Remove the end-of-sentence tag from targets.
        target = tf.slice(
            self.target, [0, 0, 0], [-1, tf.shape(self.target)[1]-1, -1])

        # Split the turn meta-info from the token ID.
        # [B, S, 10] --> [B, S, 9], [B, S, 1].
        data_meta, data_tokens = tf.split(self.data, [7, 1], axis=2)
        target_meta, target_tokens = tf.split(target, [7, 1], axis=2)

        # Embedding.
        self.embedding = tf.get_variable(
                "embedding",
                [self._hyperparams["vocab_size"],
                 self._hyperparams["embedding_size"]])

        # Look up embeddings.
        # Embeddings are shape: [B, S, 1, 300].
        encoder_inputs_embedded = tf.nn.embedding_lookup(
            self.embedding, tf.cast(data_tokens, tf.int32))
        decoder_inputs_embedded = tf.nn.embedding_lookup(
            self.embedding, tf.cast(target_tokens, tf.int32))

        # Remove '1' dimension from embeddings: [B, 1, S, 300] --> [B, S, 300].
        encoder_inputs_embedded = tf.squeeze(encoder_inputs_embedded, [2])
        decoder_inputs_embedded = tf.squeeze(decoder_inputs_embedded, [2])

        tf.add_to_collection(_CHECK, encoder_inputs_embedded)
        # tf.add_to_collection(_CHECK, decoder_inputs_embedded)

        # Merge the meta-info onto the token's embedding.
        # [B, S, 9] + [B, S, 300] --> [B, S, 309].
        encoder_inputs_embedded = tf.concat(
            [data_meta, encoder_inputs_embedded], axis=2)
        decoder_inputs_embedded = tf.concat(
            [target_meta, decoder_inputs_embedded], axis=2)

        # tf.add_to_collection(_CHECK, encoder_inputs_embedded)
        # tf.add_to_collection(_CHECK, decoder_inputs_embedded)

        # Run Dynamic RNN:
        #   encoder_outputs: [batch_size, max_time, num_units]
        #   encoder_states: [batch_size, num_units]
        with tf.variable_scope("gru_graph", reuse=tf.AUTO_REUSE):
            encoder_initial_state = self.encoder_cells.zero_state(
                tf.shape(self.data)[0], tf.float32)

        self.encoder_outputs, self.encoder_states = tf.nn.dynamic_rnn(
            self.encoder_cells, encoder_inputs_embedded, self.data_lengths,
            initial_state=encoder_initial_state)

        # tf.add_to_collection(_CHECK, self.encoder_outputs)
        # tf.add_to_collection(_CHECK, self.encoder_states)

        with tf.variable_scope("gru_graph", reuse=tf.AUTO_REUSE):
            # Vocabulary projection layer.
            projection_layer = tf.layers.Dense(
                self._hyperparams["vocab_size"], name="projection")

        # Decode.
        if open_loop:
            helper = tf.contrib.seq2seq.GreedyEmbeddingHelper(
                self.embedding,
                tf.fill([self.data.get_shape()[0]], "<SOS>"),
                "<EOS>")
            # Decoder.
            decoder = tf.contrib.seq2seq.BasicDecoder(
                self.decoder_cells,
                helper,
                self.decoder_state_inputs,
                output_layer=projection_layer)
            decoder_outputs, decoder_states, decoder_output_lengths = \
                tf.contrib.seq2seq.dynamic_decode(decoder)
            logits = decoder_outputs.sample_id
        else:
            # Subtract one from target lengths because we've stripped EOS.
            helper = tf.contrib.seq2seq.TrainingHelper(
                decoder_inputs_embedded, self.target_lengths-1)
            # Decoder.
            decoder = tf.contrib.seq2seq.BasicDecoder(
                self.decoder_cells,
                helper,
                self.decoder_state_inputs,
                output_layer=projection_layer)
            decoder_outputs, decoder_states, decoder_output_lengths = \
                tf.contrib.seq2seq.dynamic_decode(decoder)
            logits = decoder_outputs.rnn_output

        # tf.add_to_collection(_CHECK, decoder_outputs)
        # tf.add_to_collection(_CHECK, decoder_states)

        return logits

    @lazy_loading_property
    def optimize(self):
        """ Create an operation to perform an update step on the network.

        :return: Update step operation.
        """
        optimizer = tf.train.AdamOptimizer(self._hyperparams["learning_rate"])
        params = tf.trainable_variables()

        if self._hyperparams["gradient_checkpointing"]:
            gradients = memory_saving_gradients.gradients(
                self.loss, params, checkpoints="speed")
        else:
            gradients = tf.gradients(self.loss, params)

        # Gradient clipping.
        clipped_gradients, _ = tf.clip_by_global_norm(
            gradients, self._hyperparams["gradient_clip"])
        update_operation = optimizer.apply_gradients(
            zip(clipped_gradients, params))

        return update_operation

    @lazy_loading_property
    def loss(self):
        """ Calculate the loss from the decoded sequence.

        :return: Cross entropy loss (scalar).
        """
        # Set all valid timesteps to `1`, and padded timesteps to `0`.
        weights = tf.cast(tf.sequence_mask(self.target_lengths-1), tf.float32)

        # Create decoder output, it is shifted left once.
        _, target_tokens = tf.split(self.target, [7, 1], axis=2)
        target_tokens = tf.cast(tf.squeeze(target_tokens, [2]), tf.int32)
        target_tokens = tf.slice(target_tokens, [0, 1], [-1, -1])

        return tf.contrib.seq2seq.sequence_loss(
            self.inference, target_tokens, weights=weights)

    @lazy_loading_property
    def decoder_state_inputs(self):
        return self.encoder_states

    @lazy_loading_property
    def total_input_size(self):
        total = self._hyperparams["num_units"] + 7
        return total

    @lazy_loading_property
    def decoder_state_inputs(self):
        return self.encoder_states


if __name__ == "__main__":
    with tf.device("/gpu:0"):
        data = tf.placeholder(tf.float32, [None, None, 8], name="input")
        data_lengths = tf.placeholder(tf.int32, [None], name="input_lengths")
        target = tf.placeholder(tf.float32, [None, None, 8], name="target")
        target_lengths = tf.placeholder(
            tf.int32, [None], name="target_lengths")
        training = tf.placeholder(tf.bool, [], name="training")

    hparams = {
        "num_units": 300,
        "embedding_size": 300,
        # Optimization
        "learning_rate": 0.003,
        "gradient_clip": 5,
        "gradient_checkpointing": True,
        # Hardcoded.
        "vocab_size": 27000,
        "batch_size": 2,
        "activation": tf.nn.relu,
        "initializer": tf.contrib.layers.xavier_initializer(),
    }

    model = RNNGraph(
        data, data_lengths, target, target_lengths, training, hparams)

```

**Comment by yaroslavvb** [comment]
Looks like you can't save nodes inside a TensorFlow while loop (or any other control flow). Checkpointing only works for networks without control flow. Also TensorFlow already does it's own optimizations for while loop (ie, swap_memory=True to off-load activations from GPU to CPU memory) and that would interact badly with checkpointing -- https://github.com/tensorflow/tensorflow/blob/79422ab39b5fe0e1491abb8deabc7ecb5fd9f3a2/tensorflow/python/kernel_tests/rnn_test.py#L508

**Comment by MaxOSmith** [comment]
Thanks for the pointer!

**Comment by mholzel** [comment]
@yaroslavvb [Issue 675](https://github.com/tensorflow/tensorflow/issues/675), particularly [this comment](https://github.com/tensorflow/tensorflow/issues/675#issuecomment-362853672) seems to be having a similar issue. Could you perhaps take a quick look at that issue as well?

**Comment by ricsinaruto** [comment]
Does this mean that gradient checkpointing can not be used for RNN based networks? Or is there a way to define a RNN in Tensorflow without control flow ops?
